export const specialties = [
  { id: 1, name: 'Balayage', slug: 'balayage', category: 'Couleur' },
  { id: 2, name: 'Blond', slug: 'blond', category: 'Couleur' },
  { id: 3, name: 'Coloration', slug: 'coloration', category: 'Couleur' },
  { id: 4, name: 'Coupe Femme', slug: 'coupe-femme', category: 'Coupe' },
  { id: 5, name: 'Coupe Homme', slug: 'coupe-homme', category: 'Coupe' },
  { id: 6, name: 'Barber', slug: 'barber', category: 'Coupe' },
  { id: 7, name: 'Boucles', slug: 'boucles', category: 'Texture' },
  { id: 8, name: 'Extensions', slug: 'extensions', category: 'Texture' },
  { id: 9, name: 'Ombré Hair', slug: 'ombre-hair', category: 'Couleur' },
  { id: 10, name: 'Lissage', slug: 'lissage', category: 'Texture' },
  { id: 11, name: 'Mariage', slug: 'mariage', category: 'Occasion' },
  { id: 12, name: 'Hair Contouring', slug: 'hair-contouring', category: 'Couleur' },
];

export const hairdressers = [
  {
    id: 1,
    slug: 'sophie-martin',
    name: 'Sophie Martin',
    avatar: 'https://i.pravatar.cc/150?img=47',
    banner: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=1200&q=80',
    tagline: 'Experte en couleurs naturelles & balayage',
    bio: 'Passionnée par les colorations naturelles depuis 8 ans. Spécialisée dans les balayages sur mesure qui subliment chaque type de cheveux. Formée à Paris, installée à Strasbourg.',
    city: 'Strasbourg',
    avgRating: 4.9,
    reviewsCount: 47,
    followersCount: 312,
    postsCount: 28,
    yearsExperience: 8,
    isIndependent: true,
    isVerified: true,
    specialties: [
      { name: 'Balayage', slug: 'balayage' },
      { name: 'Blond', slug: 'blond' },
      { name: 'Ombré Hair', slug: 'ombre-hair' },
    ],
    instagramUrl: 'https://instagram.com',
    salon: null,
  },
  {
    id: 2,
    slug: 'lucas-bernard',
    name: 'Lucas Bernard',
    avatar: 'https://i.pravatar.cc/150?img=12',
    banner: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1200&q=80',
    tagline: 'Barber certifié — coupes homme & taille de barbe',
    bio: 'Barber depuis 6 ans, certifié par l\'école Schorem Rotterdam. Expert en coupes rétrospectives et dégradés. Chaque coupe est une sculpture.',
    city: 'Strasbourg',
    avgRating: 4.8,
    reviewsCount: 89,
    followersCount: 578,
    postsCount: 54,
    yearsExperience: 6,
    isIndependent: false,
    isVerified: true,
    specialties: [
      { name: 'Barber', slug: 'barber' },
      { name: 'Coupe Homme', slug: 'coupe-homme' },
    ],
    instagramUrl: 'https://instagram.com',
    salon: { name: 'Salon L\'Atelier', city: 'Strasbourg' },
  },
  {
    id: 3,
    slug: 'amara-diallo',
    name: 'Amara Diallo',
    avatar: 'https://i.pravatar.cc/150?img=32',
    banner: 'https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=1200&q=80',
    tagline: 'Spécialiste cheveux bouclés & textures afro',
    bio: 'Certifiée Ouidad, experte en méthode curly girl. Je comprends et sublime tous les types de boucles. Chaque texture est unique et mérite un soin sur mesure.',
    city: 'Paris',
    avgRating: 5.0,
    reviewsCount: 63,
    followersCount: 891,
    postsCount: 41,
    yearsExperience: 5,
    isIndependent: true,
    isVerified: true,
    specialties: [
      { name: 'Boucles', slug: 'boucles' },
      { name: 'Extensions', slug: 'extensions' },
      { name: 'Coloration', slug: 'coloration' },
    ],
    instagramUrl: 'https://instagram.com',
    salon: null,
  },
  {
    id: 4,
    slug: 'clara-petit',
    name: 'Clara Petit',
    avatar: 'https://i.pravatar.cc/150?img=44',
    banner: 'https://images.unsplash.com/photo-1595476589022-7c86ade2c24d?w=1200&q=80',
    tagline: 'Coupes femme & coiffures de mariée',
    bio: 'Formée à l\'IFCS Lyon, spécialisée en coupes femme et coiffures de cérémonie. Chaque cliente mérite de se sentir extraordinaire.',
    city: 'Lyon',
    avgRating: 4.7,
    reviewsCount: 34,
    followersCount: 245,
    postsCount: 19,
    yearsExperience: 4,
    isIndependent: false,
    isVerified: false,
    specialties: [
      { name: 'Coupe Femme', slug: 'coupe-femme' },
      { name: 'Mariage', slug: 'mariage' },
      { name: 'Coloration', slug: 'coloration' },
    ],
    instagramUrl: null,
    salon: { name: 'Studio Clara', city: 'Lyon' },
  },
  {
    id: 5,
    slug: 'mehdi-razzouk',
    name: 'Mehdi Razzouk',
    avatar: 'https://i.pravatar.cc/150?img=15',
    banner: 'https://images.unsplash.com/photo-1487412912498-0447578fcca8?w=1200&q=80',
    tagline: 'Coloriste — hair contouring & ombré',
    bio: 'Coloriste formé chez L\'Oréal Professionnel. Spécialiste du hair contouring pour sublimer les traits du visage par la couleur. Artiste autant que technicien.',
    city: 'Colmar',
    avgRating: 4.6,
    reviewsCount: 28,
    followersCount: 189,
    postsCount: 15,
    yearsExperience: 9,
    isIndependent: true,
    isVerified: false,
    specialties: [
      { name: 'Hair Contouring', slug: 'hair-contouring' },
      { name: 'Ombré Hair', slug: 'ombre-hair' },
      { name: 'Balayage', slug: 'balayage' },
    ],
    instagramUrl: 'https://instagram.com',
    salon: null,
  },
];

export const posts = [
  {
    id: 1,
    hairdresser: hairdressers[0],
    type: 'before_after',
    specialty: 'Balayage',
    description: 'Transformation complète — balayage naturel sur brune. Résultat en 4h de travail.',
    duration: 240,
    price: 180,
    beforeImage: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80',
    afterImage: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=800&q=80',
    coverImage: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=800&q=80',
    likesCount: 87,
    viewsCount: 423,
    createdAt: '2026-05-28',
  },
  {
    id: 2,
    hairdresser: hairdressers[1],
    type: 'result',
    specialty: 'Barber',
    description: 'Dégradé américain + taille de barbe. Le classique revisité.',
    duration: 60,
    price: 35,
    beforeImage: null,
    afterImage: null,
    coverImage: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80',
    likesCount: 124,
    viewsCount: 612,
    createdAt: '2026-05-29',
  },
  {
    id: 3,
    hairdresser: hairdressers[2],
    type: 'before_after',
    specialty: 'Boucles',
    description: 'Méthode Curly Girl appliquée — les boucles retrouvent leur définition naturelle.',
    duration: 180,
    price: 120,
    beforeImage: 'https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800&q=80',
    afterImage: 'https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=800&q=80',
    coverImage: 'https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=800&q=80',
    likesCount: 203,
    viewsCount: 981,
    createdAt: '2026-05-30',
  },
  {
    id: 4,
    hairdresser: hairdressers[3],
    type: 'result',
    specialty: 'Mariage',
    description: 'Chignon bohème pour un mariage en Provence. Accessoires en fleurs séchées.',
    duration: 150,
    price: 200,
    beforeImage: null,
    afterImage: null,
    coverImage: 'https://images.unsplash.com/photo-1595476589022-7c86ade2c24d?w=800&q=80',
    likesCount: 156,
    viewsCount: 743,
    createdAt: '2026-05-27',
  },
  {
    id: 5,
    hairdresser: hairdressers[4],
    type: 'result',
    specialty: 'Ombré Hair',
    description: 'Ombré hair cuivré sur base châtain. Fondu sur mesure selon la morphologie.',
    duration: 180,
    price: 160,
    beforeImage: null,
    afterImage: null,
    coverImage: 'https://images.unsplash.com/photo-1487412912498-0447578fcca8?w=800&q=80',
    likesCount: 94,
    viewsCount: 387,
    createdAt: '2026-05-26',
  },
  {
    id: 6,
    hairdresser: hairdressers[0],
    type: 'result',
    specialty: 'Blond',
    description: 'Blond polaire sur cheveux noirs. 3 séances de décoloration progressive.',
    duration: 300,
    price: 350,
    beforeImage: null,
    afterImage: null,
    coverImage: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80',
    likesCount: 178,
    viewsCount: 892,
    createdAt: '2026-05-25',
  },
];

export const reviews = [
  { id: 1, client: 'Marie D.', rating: 5, comment: 'Sophie est incroyable ! Mon balayage est exactement comme je le voulais. Je la recommande les yeux fermés.', specialty: 'Balayage', isVerified: true, date: '2026-05-20' },
  { id: 2, client: 'Julie K.', rating: 5, comment: 'Professionnalisme, écoute, et résultat parfait. Je suis cliente pour la vie !', specialty: 'Blond', isVerified: true, date: '2026-05-15' },
  { id: 3, client: 'Nathalie B.', rating: 4, comment: 'Très bon travail, ambiance agréable. Légèrement en retard sur l\'horaire mais le résultat vaut l\'attente.', specialty: 'Ombré Hair', isVerified: true, date: '2026-05-10' },
];
